### ISSUE TITLE
Types issue: TS2307: Cannot find module 'lighthouse/types/lhr/flow' or its corresponding type declarations

### ISSUE THREAD

**Issue by stevenwdv** [puppeteer/replay#306]
## Expected Behavior

`tsc` works fine

## Actual Behavior

```
node_modules/@puppeteer/replay/lib/main.d.ts:2:24 - error TS2307: Cannot find module 'lighthouse/types/lhr/flow' or its corresponding type declarations.
```

## Steps to Reproduce the Problem

1. Install `@puppeteer/replay`
2. Reference it in a TypeScript file
3. Compile TypeScript

## Specifications

- Version: 1.2.0, 1.2.1. Caused by #281 (e3ace90)
- Platform: Node 18.8.0, npm 8.18.1, Windows 10

**Comment by OrKoN** [comment]
@adamraine could you please take a look? It appears that that a static import for lighthouse types slipped in (but peer dependencies not yet properly defined). Should we revert?

**Comment by adamraine** [comment]
We don't need to revert the whole thing, just replace the `FlowResult` type with `any` until peer deps are added.
